=== MarsStirner/mon-pregnancy-api/api-docs/anamnesis/father/data/father_anamnesis_schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema",
    "title": "father_anamnesis_schema", 
    "description": "Схема, описывающая данные для регистрации или изменения данных анамнеза отца",
    "id": "father_anamnesis_schema",
    "type": "object",
    "properties": {
        "FIO": {
            "id": "father_anamnesis_schema/FIO",
            "type": "string",
            "description": "ФИО отца ребёнка"
        },
        "age": {
            "id": "father_anamnesis_schema/age",
            "type": "string",
            "description": "Возраст отца ребёнка"
        },
        "education": {
            "id": "father_anamnesis_schema/education",
            "type": "string",
            "description": "Код значения образования"
        },
        "work_group": {
            "id": "father_anamnesis_schema/work_group",
            "type": "string",
            "description": "Код значения общественно-профессиональной группы"
        },
        "professional_properties": {
            "id": "father_anamnesis_schema/professional_properties",
            "type": "string",
            "description": "Код значения профессиональных вредностей"
        },
        "telephone_number": {
            "id": "father_anamnesis_schema/telephone_number",
            "type": "string",
            "description": "Контактный телефонный номер отца ребенка"
        },
        "fluorography": {
            "id": "father_anamnesis_schema/fluorography",
            "type": "string",
            "description": "Сведения о флюорографии отца ребенка"
        },
        "hiv": {
            "id": "father_anamnesis_schema/hiv",
            "type": "boolean",
            "description": "Сведения о наличии заболевания ВИЧем отца ребенка"
        },
        "blood_type": {
            "id": "father_anamnesis_schema/blood_type",
            "type":"string",
            "description": "Сведения о группе крови и резус-факторе",
            "enum": [
                "0(I)Rh-",
                "0(I)Rh+",
                "A(II)Rh-",
                "A(II)Rh+",
                "B(III)Rh-",
                "B(III)Rh+",
                "AB(IV)Rh-",
                "AB(IV)Rh+",
                "0(I)RhDu",
                "A(II)RhDu",
                "B(III)RhDu",
                "AB(IV)RhDu"
            ]
        },
        "infertility": {
            "id": "father_anamnesis_schema/infertility",
            "type": "object",
            "description": "Блок информации о бесплодии в анамнезе отца ребенка, если такое имело место",
            "properties": {
                "infertility_occurence": {
                    "id": "father_anamnesis_schema/infertility/infertility_occurence",
                    "type": "boolean",
                    "description": "Наличие бесплодия в анамнезе отца ребенка"
                },
                "infertility_type": {
                    "id": "father_anamnesis_schema/infertility/infertility_type",
                    "type": "string",
                    "description": "Код значения типа бесплодия"
                },
                "infetrility_duration": {
                    "id": "father_anamnesis_schema/infertility/infetrility_duration",
                    "type": "integer",
                    "description": "Длительность бесплодия, лет"
                },
                "infertility_treatment": {
                    "id": "father_anamnesis_schema/infertility/infertility_treatment",
                    "type": "array",
                    "description": "Сведения о методах лечения бесплодия",
                    "items": {
                        "type": "string",
                        "description": "Код значения метода лечения"
                    }
                },
                "infertility_causes": {
                    "id": "father_anamnesis_schema/infertility/infertility_causes",
                    "type": "array",
                    "description": "Сведения о причинах бесплодия",
                    "items": {
                        "type": "string",
                        "description": "Код причины бесплодия"
                    }
                }
            },
            "required": [
                "infertility_occurence",
                "infertility_type",
                "infetrility_duration",
                "infertility_treatment",
                "infertility_causes"
            ]
        },
        "smoking": {
            "id": "father_anamnesis_schema/smoking",
            "type": "boolean",
            "description": "Сведения о курении"
        },
        "alcohol": {
            "id": "father_anamnesis_schema/alcohol",
            "type": "boolean",
            "description": "Сведения об алкголе"
        },
        "toxic": {
            "id": "father_anamnesis_schema/toxic",
            "type": "boolean",
            "description": "Сведения о токсических веществах"
        },
        "drugs": {
            "id": "father_anamnesis_schema/drugs",
            "type": "boolean",
            "description": "Сведения о наркотиках"
        },
        "hereditary": {
            "id": "father_anamnesis_schema/hereditary",
            "type": "array",
            "description": "Сведения о наследственных заболеваниях",
            "items": {
                "type": "string",
                "description": "Код наследственного заболевания по справочнику"
            }
        },
        "finished_diseases": {
            "id": "father_anamnesis_schema/finished_diseases",
            "type": "string",
            "description": "Сведения о перенесённых заболеваниях"
        },
        "current_diseases": {
            "id": "father_anamnesis_schema/current_diseases",
            "type": "string",
            "description": "Сведения о текущих заболеваниях отца ребенка"
        }
    }
}

=== MarsStirner/mon-pregnancy-api/api-docs/anamnesis/father/data/father-anamnesis-example.json
{
    "FIO": "Иванов Андрей Петрович",
    "age": "35",
    "education": "03",
    "work_group": "01",
    "professional_properties": "dust",
    "telephone_number": "89342134590",
    "fluorography": "Без особенностей",
    "hiv": false,
    "blood_type": "0(I)Rh-",
    "infertility": {
        "infertility_occurence": true,
        "infertility_type": "01",
        "infetrility_duration": 2,
        "infertility_treatment": ["02", "03"],
        "infertility_causes": ["02", "03"]
    },
    "smoking": false,
    "alcohol": false,
    "toxic": false,
    "drugs": false,
    "hereditary": ["01", "10"],
    "finished_diseases": "Анемия",
    "current_diseases": "Отсутствуют"
}
