=== MarsStirner/mon-pregnancy-api/api-docs/measures/data/measures_extended-list-schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "measure_list",
    "description": "Список мероприятий случая",
    "type": "array",
    "items": {
        "description": "Мероприятие случая",
        "type": "object",
        "properties": {
            "measure_id": {
                "description": "ID мероприятия случая",
                "type": "string"
            },
            "measure_type_code": {
                "description": "Код мероприятия, справочник Measure",
                "type": "string"
            },
            "appointment": {
                "title": "Appointment",
                "description": "Направление",
                "type": "object",
                "properties": {
                    "appointment_id":{
                        "type": "string",
                        "description": "id направления"
                    },
                    "appointment_code":{
                        "type": "string",
                        "description": "Уникальный код направления"
                    },
                    "appointed_date": {
                        "description": "Дата создания направления",
                        "type": "string",
                        "format": "date"
                    },
                    "appointed_lpu":{
                        "type": "string",
                        "description": "Код ЛПУ, в котором было назначено мероприятие"
                    },
                    "appointed_doctor":{
                        "type": "string",
                        "description": "Код врача, назначившего мероприятие"
                    },
                    "referral_lpu": {
                        "description": "Направлен в (код ЛПУ)",
                        "type": "string"
                    },
                    "referral_date": {
                        "description": "Дата направления (запланированная дата исполнения направления)",
                        "type": "string",
                        "format": "date"
                    },
                    "execution_time": {
                        "description": "Запланированное время исполнения",
                        "type": "string",
                        "pattern": "^([0-9]|0[0-9]|1[0-9]|2[0-3]):([0-5][0-9])$"
                    },
                    "diagnosis": {
                        "description": "Направительный диагноз",
                        "type": "string",
                        "pattern": "^([A-Z][0-9][0-9])(\\.([0-9]{1,2})(\\.[0-9]+)?)?$"
                    },
                    "indications": {
                        "description": "Показания направления (показания к госпитализации/осмотру/исследованию)",
                        "type": "string"
                    },
                    "parameters": {
                        "description": "Параметры (список)",
                        "type": "string"
                    },
                    "comment": {
                        "description": "Комментарий",
                        "type": "string"
                    },
                    "hospitalization_form": {
                        "description": "Форма госпитализации, справочник",
                        "type": "string"
                    },
                    "operation": {
                        "description": "Требуется ли операция",
                        "type": "boolean"
                    },
                    "profile": {
                        "description": "Профиль",
                        "type": "string"
                    },
                    "bed_profile": {
                        "description": "Профиль койки",
                        "type": "string"
                    }
                }
            },
            "begin_date": {
                "description": "Дата начала интервала действия мероприятия",
                "type": "string",
                "format": "date"
            },
            "end_date": {
                "description": "Дата конца интервала действия мероприятия",
                "type": "string",
                "format": "date"
            },
            "status": {
                "description": "Статус мероприятия, справочник rbMeasureStatus",
                "type": "string"
            },
            "result_action_id": {
                "description": "Результаты мероприятия, ссылка на {Action}",
                "type": "string"
            }
        },
        "required": ["measure_id", "measure_type_code", "begin_date", "end_date", "status"]
    },
    "minItems": 0
}

=== MarsStirner/mon-pregnancy-api/api-docs/measures/data/measures_extended-list-success-example.json
[
  {
    "measure_id": "measure_code_123",
    "measure_type_code": "measure_type_code_123",
    "appointment": {
      "appointment_id": "appointment_code_123",
      "appointment_number": "123321123312",
      "appointed_date": "2011-11-11",
      "appointed_lpu": "lpu_code_123",
      "appointed_doctor": "doctor_code_123",
      "referral_lpu": "lpu_code_321",
      "referral_date": "2011-11-11",
      "diagnosis": "Q00.0",
      "indications": "Грустный внешний вид"
    },
    "begin_date": "2011-11-10",
    "end_date": "2011-11-25",
    "status": "created",
    "result_action_id": "23321123"
  }
]
